class_name StarhaulResearchData
extends RefCounted


const TREE_HINT := "LMB drag to pan  |  Click node to focus  |  Hover to inspect"

const BRANCH_DEFINITIONS := [
	{"id": "propulsion", "name": "Propulsion", "color": Color(0.58, 0.9, 1.0), "summary": "Flight systems, boost handling, and map-jump efficiency."},
	{"id": "industry", "name": "Industry", "color": Color(0.99, 0.82, 0.45), "summary": "Refining, production efficiency, and later shipboard fabrication."},
	{"id": "systems", "name": "Systems", "color": Color(0.78, 0.88, 1.0), "summary": "Scanner packages, ship operations, and utility electronics."},
	{"id": "salvage", "name": "Salvage", "color": Color(0.92, 0.68, 0.54), "summary": "Recovery doctrine, wreck processing, and derelict handling."},
	{"id": "combat", "name": "Combat", "color": Color(1.0, 0.45, 0.42), "summary": "Weapons, tactical systems, survivability, and combat payouts."},
]

const RESEARCH_NODES := [
	# --- Industry ---
	{
		"id": "ore_refinement_basics",
		"branch": "industry",
		"title": "Ore Refinement Basics",
		"summary": "Unlocks cleaner refinery handling",
		"description": "You learn the basics of ore refinement and proper ore refinement procedures and protocols",
		"tier": 1,
		"column": 0,
		"row_offset": 0.0,
		"parents": [],
		"status": "PLANNED",
		"max_rank": 1,
		"unit_cost": 1,
		"credit_cost": 180,
		"effect_key": "industry_unlock",
		"effect_per_rank": 1.0,
		"effect_summary": "Unlocks follow-up Industry training nodes.",
		"cost_summary": "1 research unit + 180 credits",
	},
	{
		"id": "refinery_throughput",
		"branch": "industry",
		"title": "Refinery Throughput",
		"summary": "Faster refining cycles",
		"description": "Improves processing cadence and keeps the refinery queue moving.",
		"tier": 2,
		"column": 1,
		"row_offset": -220.0,
		"parents": ["ore_refinement_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 140,
		"effect_key": "refinery_throughput_bonus",
		"effect_per_rank": 0.05,
		"effect_summary": "+5% refinery throughput per rank.",
		"cost_summary": "1 research unit + 140 credits per rank",
	},
	{
		"id": "cost_control",
		"branch": "industry",
		"title": "Cost Control",
		"summary": "Lower station refine fees",
		"description": "Cuts waste and service overhead inside the station refinery.",
		"tier": 2,
		"column": 1,
		"row_offset": 0.0,
		"parents": ["ore_refinement_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 120,
		"effect_key": "research_refinery_fee_discount",
		"effect_per_rank": 0.04,
		"effect_summary": "-4% refinery cost per rank.",
		"cost_summary": "1 research unit + 120 credits per rank",
	},
	{
		"id": "industrial_yield",
		"branch": "industry",
		"title": "Industrial Yield",
		"summary": "Improved refined output",
		"description": "Tightens industrial handling so a little more usable product survives each batch.",
		"tier": 2,
		"column": 1,
		"row_offset": 220.0,
		"parents": ["ore_refinement_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_refinery_output_bonus",
		"effect_per_rank": 0.04,
		"effect_summary": "+4% refined output efficiency per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "advanced_separation",
		"branch": "industry",
		"title": "Advanced Separation",
		"summary": "Better trace recovery",
		"description": "Introduces more sophisticated recovery methods for mixed ore and rarer feedstock.",
		"tier": 3,
		"column": 2,
		"row_offset": -140.0,
		"parents": ["refinery_throughput"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 260,
		"effect_key": "research_rare_recovery_bonus",
		"effect_per_rank": 0.03,
		"effect_summary": "+3% rare recovery chance per rank.",
		"cost_summary": "2 research units + 260 credits per rank",
	},
	{
		"id": "catalytic_refining",
		"branch": "industry",
		"title": "Catalytic Refining",
		"summary": "More efficient station batches",
		"description": "Upgrades catalytic handling inside the dock refinery.",
		"tier": 3,
		"column": 2,
		"row_offset": 120.0,
		"parents": ["cost_control", "industrial_yield"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 280,
		"effect_key": "research_catalytic_efficiency",
		"effect_per_rank": 0.02,
		"effect_summary": "+4% refinery speed and +2% output efficiency per rank.",
		"cost_summary": "2 research units + 280 credits per rank",
	},
	{
		"id": "batch_processing",
		"branch": "industry",
		"title": "Batch Processing",
		"summary": "Supports larger industrial runs",
		"description": "Builds toward a more serious industrial identity for the ship and station.",
		"tier": 4,
		"column": 3,
		"row_offset": 0.0,
		"parents": ["advanced_separation", "catalytic_refining"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 3,
		"credit_cost": 420,
		"effect_key": "research_batch_processing_bonus",
		"effect_per_rank": 0.05,
		"effect_summary": "+5% batch size/output handling per rank.",
		"cost_summary": "3 research units + 420 credits per rank",
	},

	# --- Propulsion ---
	{
		"id": "thruster_calibration",
		"branch": "propulsion",
		"title": "Thruster Calibration",
		"summary": "Improved base flight response",
		"description": "Refines basic thrust vector behavior and opens the Propulsion lane for broader flight-system work.",
		"tier": 1,
		"column": 0,
		"row_offset": 0.0,
		"parents": [],
		"status": "PLANNED",
		"max_rank": 1,
		"unit_cost": 1,
		"credit_cost": 170,
		"effect_key": "propulsion_unlock",
		"effect_per_rank": 1.0,
		"effect_summary": "Unlocks the first flight upgrades.",
		"cost_summary": "1 research unit + 170 credits",
	},
	{
		"id": "vector_nozzles",
		"branch": "propulsion",
		"title": "Vector Nozzles",
		"summary": "Higher cruise speed",
		"description": "Improves thrust shaping for a modest but noticeable increase in straight-line travel speed.",
		"tier": 2,
		"column": 1,
		"row_offset": -180.0,
		"parents": ["thruster_calibration"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_engine_speed_bonus",
		"effect_per_rank": 0.04,
		"effect_summary": "+4% ship speed per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "thrust_balancing",
		"branch": "propulsion",
		"title": "Thrust Balancing",
		"summary": "Sharper acceleration",
		"description": "Reduces wasted thrust during maneuver changes, making acceleration feel more responsive without changing the whole ship identity.",
		"tier": 2,
		"column": 1,
		"row_offset": 0.0,
		"parents": ["thruster_calibration"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_engine_acceleration_bonus",
		"effect_per_rank": 0.05,
		"effect_summary": "+5% ship acceleration per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "boost_reclaim",
		"branch": "propulsion",
		"title": "Boost Reclaim",
		"summary": "Cheaper boost burns",
		"description": "Recovers a bit more energy during boost cycling and lowers fuel cost during sustained bursts.",
		"tier": 2,
		"column": 1,
		"row_offset": 180.0,
		"parents": ["thruster_calibration"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 145,
		"effect_key": "research_boost_efficiency",
		"effect_per_rank": 0.05,
		"effect_summary": "-5% boost fuel burn per rank.",
		"cost_summary": "1 research unit + 145 credits per rank",
	},
	{
		"id": "reserve_tanks",
		"branch": "propulsion",
		"title": "Reserve Tanks",
		"summary": "Slightly larger fuel reserve",
		"description": "Adds modest storage and line-routing improvements to stretch expedition time without trivializing fuel planning.",
		"tier": 3,
		"column": 2,
		"row_offset": -90.0,
		"parents": ["vector_nozzles", "thrust_balancing"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 240,
		"effect_key": "research_fuel_capacity_bonus",
		"effect_per_rank": 0.06,
		"effect_summary": "+6% fuel capacity per rank.",
		"cost_summary": "2 research units + 240 credits per rank",
	},
	{
		"id": "jump_economy",
		"branch": "propulsion",
		"title": "Jump Economy",
		"summary": "Cheaper local map jumps",
		"description": "Trims jump-system overhead and keeps local navigation from draining the tanks too aggressively.",
		"tier": 3,
		"column": 2,
		"row_offset": 120.0,
		"parents": ["boost_reclaim"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 2,
		"credit_cost": 250,
		"effect_key": "research_map_jump_efficiency",
		"effect_per_rank": 0.05,
		"effect_summary": "-5% local map jump fuel cost per rank.",
		"cost_summary": "2 research units + 250 credits per rank",
	},
	{
		"id": "flight_control_matrix",
		"branch": "propulsion",
		"title": "Flight Control Matrix",
		"summary": "Refined all-around handling",
		"description": "A final pass on flight-control logic that ties speed, acceleration, and efficiency upgrades together into a steadier piloting feel.",
		"tier": 4,
		"column": 3,
		"row_offset": 0.0,
		"parents": ["reserve_tanks", "jump_economy"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 3,
		"credit_cost": 390,
		"effect_key": "research_propulsion_matrix",
		"effect_per_rank": 0.03,
		"effect_summary": "+3% speed and +3% acceleration per rank.",
		"cost_summary": "3 research units + 390 credits per rank",
	},

	# --- Systems ---
	{
		"id": "scanner_foundations",
		"branch": "systems",
		"title": "Scanner Foundations",
		"summary": "Baseline scan package discipline",
		"description": "Training for proper use of onboard electronics and ship electronics upkeep.",
		"tier": 1,
		"column": 0,
		"row_offset": 0.0,
		"parents": [],
		"status": "PLANNED",
		"max_rank": 1,
		"unit_cost": 1,
		"credit_cost": 180,
		"effect_key": "systems_unlock",
		"effect_per_rank": 1.0,
		"effect_summary": "Unlocks first utility electronics upgrades.",
		"cost_summary": "1 research unit + 180 credits",
	},
	{
		"id": "faster_readbacks",
		"branch": "systems",
		"title": "Faster Readbacks",
		"summary": "Lower scanner cooldown",
		"description": "Optimizes sensor processing and shortens recovery time between active scans.",
		"tier": 2,
		"column": 1,
		"row_offset": -180.0,
		"parents": ["scanner_foundations"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_scan_cooldown_bonus",
		"effect_per_rank": 0.05,
		"effect_summary": "-5% active scan cooldown per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "signal_archiving",
		"branch": "systems",
		"title": "Signal Archiving",
		"summary": "Better Data Fragment yields",
		"description": "Improves signal capture and lets the ship squeeze a bit more usable research data out of targeted scans.",
		"tier": 2,
		"column": 1,
		"row_offset": 0.0,
		"parents": ["scanner_foundations"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 155,
		"effect_key": "research_scan_data_bonus",
		"effect_per_rank": 0.08,
		"effect_summary": "+8% Data Fragment gain per rank.",
		"cost_summary": "1 research unit + 155 credits per rank",
	},
	{
		"id": "contact_tagging",
		"branch": "systems",
		"title": "Contact Tagging",
		"summary": "Clearer tracked signatures",
		"description": "Stabilizes tracked contacts and adds enough sensor certainty to hold useful guidance longer in busy areas.",
		"tier": 2,
		"column": 1,
		"row_offset": 180.0,
		"parents": ["scanner_foundations"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 1,
		"credit_cost": 145,
		"effect_key": "research_tracking_suite",
		"effect_per_rank": 0.1,
		"effect_summary": "Improves tracking suite stability.",
		"cost_summary": "1 research unit + 145 credits per rank",
	},
	{
		"id": "deep_spectrum_filters",
		"branch": "systems",
		"title": "Deep Spectrum Filters",
		"summary": "Richer scan payouts on rare targets",
		"description": "Adds deeper signal filtering that favors meaningful contacts like derelicts, suns, and unusual signatures.",
		"tier": 3,
		"column": 2,
		"row_offset": -100.0,
		"parents": ["faster_readbacks", "signal_archiving"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 250,
		"effect_key": "research_scan_rare_bonus",
		"effect_per_rank": 0.1,
		"effect_summary": "+10% DF yield on high-value scans per rank.",
		"cost_summary": "2 research units + 250 credits per rank",
	},
	{
		"id": "systems_bus_trim",
		"branch": "systems",
		"title": "Systems Bus Trim",
		"summary": "General ship utility efficiency",
		"description": "A small systems-wide cleanup pass that improves power delivery and supports broader operations without stealing power from other systems.",
		"tier": 3,
		"column": 2,
		"row_offset": 120.0,
		"parents": ["contact_tagging"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 240,
		"effect_key": "research_systems_trim",
		"effect_per_rank": 0.03,
		"effect_summary": "-3% standard fuel burn and -3% scan cooldown per rank.",
		"cost_summary": "2 research units + 240 credits per rank",
	},
	{
		"id": "survey_uplink",
		"branch": "systems",
		"title": "Survey Uplink",
		"summary": "High-grade research data relay",
		"description": "Upgrade scanner systems to to deepen scan results and add better scanner cooling.",
		"tier": 4,
		"column": 3,
		"row_offset": 0.0,
		"parents": ["deep_spectrum_filters", "systems_bus_trim"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 3,
		"credit_cost": 400,
		"effect_key": "research_uplink_suite",
		"effect_per_rank": 0.05,
		"effect_summary": "+5% scan data gain and -2% scan cooldown per rank.",
		"cost_summary": "3 research units + 400 credits per rank",
	},

	# --- Salvage ---
	{
		"id": "recovery_basics",
		"branch": "salvage",
		"title": "Recovery Basics",
		"summary": "Opens structured salvage work",
		"description": "Formalizes wreck recovery methods and safety training",
		"tier": 1,
		"column": 0,
		"row_offset": 0.0,
		"parents": [],
		"status": "PLANNED",
		"max_rank": 1,
		"unit_cost": 1,
		"credit_cost": 175,
		"effect_key": "salvage_unlock",
		"effect_per_rank": 1.0,
		"effect_summary": "Unlocks the first recovery improvements.",
		"cost_summary": "1 research unit + 175 credits",
	},
	{
		"id": "wreck_stripping",
		"branch": "salvage",
		"title": "Wreck Stripping",
		"summary": "Higher salvage output",
		"description": "Improves the practical yield you pull from salvage targets.",
		"tier": 2,
		"column": 1,
		"row_offset": -180.0,
		"parents": ["recovery_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 145,
		"effect_key": "research_salvage_yield_bonus",
		"effect_per_rank": 0.06,
		"effect_summary": "+6% salvage yield per rank.",
		"cost_summary": "1 research unit + 145 credits per rank",
	},
	{
		"id": "cache_recovery",
		"branch": "salvage",
		"title": "Cache Recovery",
		"summary": "Better derelict cache pulls",
		"description": "Teaches how to identify and recover useful sealed caches before they break apart in the field.",
		"tier": 2,
		"column": 1,
		"row_offset": 0.0,
		"parents": ["recovery_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 145,
		"effect_key": "research_derelict_cache_bonus",
		"effect_per_rank": 0.08,
		"effect_summary": "+8% derelict cache bonus per rank.",
		"cost_summary": "1 research unit + 145 credits per rank",
	},
	{
		"id": "boarding_protocols",
		"branch": "salvage",
		"title": "Boarding Protocols",
		"summary": "Richer boarding outcomes",
		"description": "Improves boarding discipline and raises the value of recovered lockers, avionics, and loose system salvage.",
		"tier": 2,
		"column": 1,
		"row_offset": 180.0,
		"parents": ["recovery_basics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 155,
		"effect_key": "research_boarding_loot_bonus",
		"effect_per_rank": 0.1,
		"effect_summary": "+10% boarding loot quality per rank.",
		"cost_summary": "1 research unit + 155 credits per rank",
	},
	{
		"id": "derelict_indexing",
		"branch": "salvage",
		"title": "Derelict Indexing",
		"summary": "Higher-value wreck scans",
		"description": "Improves derelict signal classification and turns meaningful wreck scans into stronger research data sources.",
		"tier": 3,
		"column": 2,
		"row_offset": -90.0,
		"parents": ["wreck_stripping", "cache_recovery"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 250,
		"effect_key": "research_derelict_scan_bonus",
		"effect_per_rank": 0.12,
		"effect_summary": "+12% DF from derelict scans per rank.",
		"cost_summary": "2 research units + 250 credits per rank",
	},
	{
		"id": "recovery_vectors",
		"branch": "salvage",
		"title": "Recovery Vectors",
		"summary": "Cleaner field recovery loops",
		"description": "Coordinates salvage handling more cleanly and makes sustained derelict work feel more efficient across repeated runs.",
		"tier": 3,
		"column": 2,
		"row_offset": 120.0,
		"parents": ["boarding_protocols"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 235,
		"effect_key": "research_salvage_vectors",
		"effect_per_rank": 0.04,
		"effect_summary": "+4% salvage yield and +4% cache recovery per rank.",
		"cost_summary": "2 research units + 235 credits per rank",
	},
	{
		"id": "priority_reclamation",
		"branch": "salvage",
		"title": "Priority Reclamation",
		"summary": "Elite salvage handling",
		"description": "Pushes the lane toward specialist wreck work and later boarding/interior systems while still paying off in the current salvage loop.",
		"tier": 4,
		"column": 3,
		"row_offset": 0.0,
		"parents": ["derelict_indexing", "recovery_vectors"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 3,
		"credit_cost": 405,
		"effect_key": "research_priority_reclamation",
		"effect_per_rank": 0.05,
		"effect_summary": "+5% salvage yield, +5% boarding loot, and +5% derelict cache value per rank.",
		"cost_summary": "3 research units + 405 credits per rank",
	},

	# --- Combat ---
	{
		"id": "weapons_diagnostics",
		"branch": "combat",
		"title": "Weapons Diagnostics",
		"summary": "Structured combat systems baseline",
		"description": "Runs the first serious diagnostics pass on weapon control.",
		"tier": 1,
		"column": 0,
		"row_offset": 0.0,
		"parents": [],
		"status": "PLANNED",
		"max_rank": 1,
		"unit_cost": 1,
		"credit_cost": 180,
		"effect_key": "combat_unlock",
		"effect_per_rank": 1.0,
		"effect_summary": "Unlocks the Combat lane and the first tactical upgrades.",
		"cost_summary": "1 research unit + 180 credits",
	},
	{
		"id": "lock_painting",
		"branch": "combat",
		"title": "Lock Painting",
		"summary": "Faster missile locks",
		"description": "Improves target acquisition timing.",
		"tier": 2,
		"column": 1,
		"row_offset": -180.0,
		"parents": ["weapons_diagnostics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_combat_lock_bonus",
		"effect_per_rank": 0.06,
		"effect_summary": "-6% missile lock time per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "rack_cycling",
		"branch": "combat",
		"title": "Rack Cycling",
		"summary": "Lower missile cooldowns",
		"description": "Shortens missile handling delays and lowering special weapons cooldowns.",
		"tier": 2,
		"column": 1,
		"row_offset": 0.0,
		"parents": ["weapons_diagnostics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 150,
		"effect_key": "research_missile_cooldown_bonus",
		"effect_per_rank": 0.06,
		"effect_summary": "-6% missile cooldown per rank.",
		"cost_summary": "1 research unit + 150 credits per rank",
	},
	{
		"id": "armor_doctrine",
		"branch": "combat",
		"title": "Armor Doctrine",
		"summary": "Improved hull survivability",
		"description": "Refines combat survival expectations and modestly raises effective hull tolerance.",
		"tier": 2,
		"column": 1,
		"row_offset": 180.0,
		"parents": ["weapons_diagnostics"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 1,
		"credit_cost": 160,
		"effect_key": "research_hull_bonus",
		"effect_per_rank": 5.0,
		"effect_summary": "+5 hull capacity per rank.",
		"cost_summary": "1 research unit + 160 credits per rank",
	},
	{
		"id": "combat_ledger",
		"branch": "combat",
		"title": "Combat Ledger",
		"summary": "Higher bounty returns",
		"description": "Improves bounty payout though standardized combat logging systems.",
		"tier": 3,
		"column": 2,
		"row_offset": -90.0,
		"parents": ["lock_painting", "rack_cycling"],
		"status": "PLANNED",
		"max_rank": 3,
		"unit_cost": 2,
		"credit_cost": 255,
		"effect_key": "research_bounty_bonus",
		"effect_per_rank": 0.08,
		"effect_summary": "+8% bounty payout per rank.",
		"cost_summary": "2 research units + 255 credits per rank",
	},
	{
		"id": "damage_control",
		"branch": "combat",
		"title": "Damage Control",
		"summary": "More resilient combat state",
		"description": "Improves emergency recovery discipline.",
		"tier": 3,
		"column": 2,
		"row_offset": 120.0,
		"parents": ["armor_doctrine"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 2,
		"credit_cost": 245,
		"effect_key": "research_damage_control",
		"effect_per_rank": 4.0,
		"effect_summary": "+4 hull capacity per rank.",
		"cost_summary": "2 research units + 245 credits per rank",
	},
	{
		"id": "tactical_firing_net",
		"branch": "combat",
		"title": "Tactical Firing Net",
		"summary": "Integrated weapons discipline",
		"description": "Connects lock, cooldown, and combat recovery work into a more complete tactical package.",
		"tier": 4,
		"column": 3,
		"row_offset": 0.0,
		"parents": ["combat_ledger", "damage_control"],
		"status": "PLANNED",
		"max_rank": 2,
		"unit_cost": 3,
		"credit_cost": 410,
		"effect_key": "research_tactical_net",
		"effect_per_rank": 0.03,
		"effect_summary": "-3% lock time and -3% missile cooldown per rank.",
		"cost_summary": "3 research units + 410 credits per rank",
	},
]


static func branch_definitions() -> Array:
	return BRANCH_DEFINITIONS


static func nodes() -> Array:
	return RESEARCH_NODES
