class_name StarhaulMissionData
extends RefCounted


const STARHAUL_DATA_LIB := preload("res://scripts/starhaul_data.gd")


static func mission_templates() -> Array[Dictionary]:
	return [
		{
			"id": "mine_ore",
			"progress_key": "mine_ore",
			"short_name": "Iron Sweep",
			"description": "Bring 16 Iron Ore back for the dock foundry crews.",
			"faction": "deepcore_consortium",
			"rep_reward": 8,
			"goal": 16,
			"target_label": "Iron asteroid fields",
			"deliver_item": STARHAUL_DATA_LIB.ORE,
			"deliver_amount": 16,
			"required_mining_stage": 0,
			"reward_credits": 115,
			"reward_xp": 34,
		},
		{
			"id": "nickel_pull",
			"progress_key": "mine_ore",
			"short_name": "Nickel Pull",
			"description": "Bring 12 Nickel Ore back for a fresh industrial alloy run.",
			"faction": "deepcore_consortium",
			"rep_reward": 9,
			"goal": 12,
			"target_label": "Nickel asteroid fields",
			"deliver_item": STARHAUL_DATA_LIB.NICKEL,
			"deliver_amount": 12,
			"required_mining_stage": 1,
			"reward_credits": 132,
			"reward_xp": 38,
			"min_rank": "Recruit",
		},
		{
			"id": "copper_pull",
			"progress_key": "mine_ore",
			"short_name": "Copper Pull",
			"description": "Bring 12 Copper Ore back before the local fabrication queue stalls.",
			"faction": "deepcore_consortium",
			"rep_reward": 10,
			"goal": 12,
			"target_label": "Copper asteroid fields",
			"deliver_item": STARHAUL_DATA_LIB.COPPER,
			"deliver_amount": 12,
			"required_mining_stage": 1,
			"reward_credits": 144,
			"reward_xp": 42,
			"min_rank": "Recruit",
		},
		{
			"id": "foundry_quota",
			"progress_key": "mine_ore",
			"short_name": "Titanium Quota",
			"description": "Bring 10 Titanium Ore in for a priority hull fabrication batch.",
			"faction": "deepcore_consortium",
			"rep_reward": 12,
			"goal": 10,
			"target_label": "Titanium asteroid fields",
			"deliver_item": STARHAUL_DATA_LIB.TITANIUM,
			"deliver_amount": 10,
			"required_mining_stage": 2,
			"reward_credits": 196,
			"reward_xp": 58,
			"min_rank": "Cadet",
		},
		{
			"id": "gold_claim",
			"progress_key": "mine_ore",
			"short_name": "Gold Claim",
			"description": "Bring 6 Gold Ore back under seal for a broker-priority payout.",
			"faction": "freeport_assembly",
			"rep_reward": 13,
			"goal": 6,
			"target_label": "Gold vein contacts",
			"deliver_item": STARHAUL_DATA_LIB.GOLD,
			"deliver_amount": 6,
			"required_mining_stage": 3,
			"reward_credits": 212,
			"reward_xp": 62,
			"min_rank": "Cadet",
		},
		{
			"id": "lindrite_charter",
			"progress_key": "mine_ore",
			"short_name": "Lindrite Charter",
			"description": "Bring 4 Lindrite Ore back for restricted Deepcore analysis.",
			"faction": "deepcore_consortium",
			"rep_reward": 18,
			"goal": 4,
			"target_label": "Lindrite geode signals",
			"deliver_item": STARHAUL_DATA_LIB.LINDRITE,
			"deliver_amount": 4,
			"required_mining_stage": 3,
			"reward_credits": 288,
			"reward_xp": 82,
			"min_rank": "Operative",
		},
		{
			"id": "iridium_charter",
			"progress_key": "mine_ore",
			"short_name": "Iridium Charter",
			"description": "Deepcore wants rare ore cores secured for a controlled industrial run.",
			"faction": "deepcore_consortium",
			"rep_reward": 16,
			"goal": 20,
			"target_label": "Rare ore signatures",
			"deliver_item": STARHAUL_DATA_LIB.IRIDIUM,
			"deliver_amount": 2,
			"required_mining_stage": 3,
			"reward_credits": 260,
			"reward_xp": 76,
			"min_rank": "Operative",
		},
		{
			"id": "mine_crystal",
			"progress_key": "mine_crystal",
			"short_name": "Crystal Request",
			"description": "Recover crystal lattice stock for station research buyers.",
			"faction": "pathfinder_initiative",
			"rep_reward": 9,
			"goal": 8,
			"target_label": "Crystal clusters",
			"deliver_item": STARHAUL_DATA_LIB.CRYSTAL,
			"deliver_amount": 8,
			"reward_credits": 145,
			"reward_xp": 42,
		},
		{
			"id": "survey_sweep",
			"progress_key": "scan_resources",
			"short_name": "Survey Sweep",
			"description": "Pathfinder surveyors need fresh resource scans on promising fields.",
			"faction": "pathfinder_initiative",
			"rep_reward": 8,
			"goal": 3,
			"target_label": "Resource contacts",
			"reward_credits": 120,
			"reward_xp": 34,
		},
		{
			"id": "hostile_probe",
			"progress_key": "scan_hostiles",
			"short_name": "Threat Probe",
			"description": "Pathfinder wants clean hostile telemetry before survey crews move deeper into the lane.",
			"faction": "pathfinder_initiative",
			"rep_reward": 10,
			"goal": 2,
			"target_label": "Hostile signatures",
			"reward_credits": 140,
			"reward_xp": 40,
			"min_rank": "Cadet",
		},
		{
			"id": "deep_vector_survey",
			"progress_key": "scan_resources",
			"short_name": "Deep Vector Survey",
			"description": "Run a broader scan package and pin down high-value resource contacts for the next survey wave.",
			"faction": "pathfinder_initiative",
			"rep_reward": 15,
			"goal": 5,
			"target_label": "Advanced resource contacts",
			"reward_credits": 215,
			"reward_xp": 66,
			"min_rank": "Operative",
		},
		{
			"id": "mine_ice",
			"progress_key": "mine_ice",
			"short_name": "Fuel Ice Haul",
			"description": "Mine volatile ice for the refinery fuel queue.",
			"faction": "freeport_assembly",
			"rep_reward": 7,
			"goal": 12,
			"target_label": "Ice masses",
			"deliver_item": STARHAUL_DATA_LIB.ICE,
			"deliver_amount": 12,
			"reward_credits": 100,
			"reward_xp": 30,
		},
		{
			"id": "trade_circuit",
			"progress_key": "sell_value",
			"short_name": "Trade Circuit",
			"description": "Freeport brokers need a larger exchange payout cycle cleared today.",
			"faction": "freeport_assembly",
			"rep_reward": 11,
			"goal": 340,
			"target_label": "Orbital Dock exchange",
			"reward_credits": 185,
			"reward_xp": 54,
			"min_rank": "Cadet",
		},
		{
			"id": "fuel_exchange",
			"progress_key": "refine_goods",
			"short_name": "Fuel Cell Lot",
			"description": "Freeport brokers need refined fuel cells moved through the exchange before the market cools.",
			"faction": "freeport_assembly",
			"rep_reward": 12,
			"goal": 6,
			"target_label": "Orbital Dock exchange",
			"deliver_item": STARHAUL_DATA_LIB.FUEL_CELL,
			"deliver_amount": 6,
			"reward_credits": 205,
			"reward_xp": 56,
			"min_rank": "Cadet",
		},
		{
			"id": "salvage_scrap",
			"progress_key": "mission_delivery",
			"short_name": "Derelict Recovery",
			"description": "Locate a marked courier hulk, strip it for a relay core, and bring the part home.",
			"faction": "recovery_corps",
			"rep_reward": 9,
			"goal": 1,
			"target_label": "Courier derelict contact",
			"mission_derelict_profile": "courier_hulk",
			"deliver_item": STARHAUL_DATA_LIB.ANCIENT_RELIC,
			"deliver_amount": 1,
			"reward_credits": 110,
			"reward_xp": 32,
		},
		{
			"id": "priority_recovery",
			"progress_key": "mission_delivery",
			"short_name": "Priority Recovery",
			"description": "Recovery Corps flagged a survey hulk with an intact quantum cache. Recover the shard.",
			"faction": "recovery_corps",
			"rep_reward": 12,
			"goal": 1,
			"target_label": "Survey derelict contact",
			"mission_derelict_profile": "research_hulk",
			"deliver_item": STARHAUL_DATA_LIB.QUANTUM_SHARD,
			"deliver_amount": 1,
			"reward_credits": 175,
			"reward_xp": 52,
			"min_rank": "Cadet",
		},
		{
			"id": "contested_recovery",
			"progress_key": "mission_delivery",
			"short_name": "Contested Recovery",
			"description": "Recovery Corps marked an armed patrol hulk. Recover its targeting array before raiders do.",
			"faction": "recovery_corps",
			"rep_reward": 14,
			"goal": 1,
			"target_label": "Contested patrol derelict",
			"mission_derelict_profile": "patrol_hulk",
			"deliver_item": STARHAUL_DATA_LIB.TARGETING_ARRAY,
			"deliver_amount": 1,
			"reward_credits": 205,
			"reward_xp": 62,
			"min_rank": "Cadet",
		},
		{
			"id": "derelict_quarantine",
			"progress_key": "blackwake_kills",
			"short_name": "Derelict Quarantine",
			"description": "Paladins want Blackwake scavengers cleared off a vulnerable derelict before recovery crews move in.",
			"faction": "paladins",
			"rep_reward": 13,
			"goal": 3,
			"target_label": "Derelict quarantine zone",
			"reward_credits": 195,
			"reward_xp": 60,
			"min_rank": "Cadet",
		},
		{
			"id": "sealed_cache",
			"progress_key": "mission_delivery",
			"short_name": "Sealed Cache",
			"description": "Recovery Corps marked a freighter hulk with a sealed isotope bay. Recover the helium cache.",
			"faction": "recovery_corps",
			"rep_reward": 16,
			"goal": 1,
			"target_label": "Freighter derelict contact",
			"mission_derelict_profile": "freighter_hulk",
			"deliver_item": STARHAUL_DATA_LIB.HELIUM3,
			"deliver_amount": 1,
			"reward_credits": 245,
			"reward_xp": 74,
			"min_rank": "Operative",
		},
		{
			"id": "sell_value",
			"progress_key": "sell_value",
			"short_name": "Market Delivery",
			"description": "Sell enough cargo to hit the station's payout quota.",
			"faction": "freeport_assembly",
			"rep_reward": 8,
			"goal": 220,
			"target_label": "Orbital Dock exchange",
			"reward_credits": 135,
			"reward_xp": 38,
		},
		{
			"id": "refine_goods",
			"progress_key": "refine_goods",
			"short_name": "Refinery Order",
			"description": "Process raw goods into refined station-ready inventory.",
			"faction": "deepcore_consortium",
			"rep_reward": 9,
			"goal": 10,
			"target_label": "Orbital Dock refinery",
			"deliver_item": STARHAUL_DATA_LIB.ALLOY,
			"deliver_amount": 10,
			"reward_credits": 125,
			"reward_xp": 36,
		},
		{
			"id": "bulk_alloy_order",
			"progress_key": "refine_goods",
			"short_name": "Bulk Alloy Order",
			"description": "Deepcore wants a larger refined alloy batch pushed through the dock refinery on priority.",
			"faction": "deepcore_consortium",
			"rep_reward": 13,
			"goal": 16,
			"target_label": "Orbital Dock refinery",
			"deliver_item": STARHAUL_DATA_LIB.ALLOY,
			"deliver_amount": 16,
			"reward_credits": 190,
			"reward_xp": 58,
			"min_rank": "Cadet",
		},
		{
			"id": "buy_upgrade",
			"progress_key": "buy_upgrade",
			"short_name": "Outfit Pass",
			"description": "Install a ship upgrade and certify the hull for tougher work.",
			"faction": "paladins",
			"rep_reward": 6,
			"goal": 1,
			"target_label": "Orbital Dock shipyard",
			"reward_credits": 90,
			"reward_xp": 28,
		},
		{
			"id": "blackwake_kills",
			"progress_key": "blackwake_kills",
			"short_name": "Raider Sweep",
			"description": "Clear local Blackwake raiders off the station approach lanes.",
			"faction": "paladins",
			"rep_reward": 10,
			"goal": 3,
			"target_label": "Blackwake contacts",
			"reward_credits": 150,
			"reward_xp": 44,
		},
		{
			"id": "bounty_tags",
			"progress_key": "bounty_tags",
			"short_name": "Cipher Collection",
			"description": "Paladins are paying for recovered Blackwake cipher tags from recent patrol actions.",
			"faction": "paladins",
			"rep_reward": 9,
			"goal": 2,
			"target_label": "Blackwake bounty pickups",
			"deliver_item": STARHAUL_DATA_LIB.BLACKWAKE_TAG,
			"deliver_amount": 2,
			"reward_credits": 140,
			"reward_xp": 40,
		},
		{
			"id": "blackwake_hunt",
			"progress_key": "blackwake_kills",
			"short_name": "Lane Interdiction",
			"description": "Paladins request a tougher sweep to break up a Blackwake strike wing.",
			"faction": "paladins",
			"rep_reward": 14,
			"goal": 5,
			"target_label": "Blackwake contacts",
			"reward_credits": 220,
			"reward_xp": 68,
			"min_rank": "Cadet",
		},
		{
			"id": "breacher_breakup",
			"progress_key": "blackwake_kills",
			"short_name": "Breacher Breakup",
			"description": "Paladins want heavier Blackwake breachers cleared before they can crack disabled ships open.",
			"faction": "paladins",
			"rep_reward": 17,
			"goal": 6,
			"target_label": "Heavy Blackwake contacts",
			"reward_credits": 285,
			"reward_xp": 82,
			"min_rank": "Operative",
		},
	]


static func intro_mission_templates() -> Array[Dictionary]:
	return [
		{
			"id": "intro_welcome",
			"progress_key": "intro_welcome",
			"short_name": "Welcome Player",
			"description": "Read the welcome briefing and prepare to begin guided operations training.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Flight training briefing",
			"reward_credits": 20,
			"reward_xp": 0,
			"intro": true,
			"intro_forced": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_next": "intro_flight_controls",
		},
		{
			"id": "intro_flight_controls",
			"progress_key": "intro_move",
			"short_name": "Flight Controls Check Mission",
			"description": "Move the ship under manual control and prove you can handle basic flight.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Flight lane check",
			"reward_credits": 28,
			"reward_xp": 0,
			"intro": true,
			"intro_forced": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_welcome"],
			"intro_next": "intro_head_to_board",
		},
		{
			"id": "intro_head_to_board",
			"progress_key": "intro_open_mission_board",
			"short_name": "Head to Mission Board in Station",
			"description": "Return to Orbital Dock and open the mission board to access the introduction contracts.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock mission board",
			"reward_credits": 36,
			"reward_xp": 0,
			"intro": true,
			"intro_forced": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_flight_controls"],
		},
		{
			"id": "intro_tab_menu",
			"progress_key": "intro_tab_menu",
			"short_name": "TAB Menu Mission",
			"description": "Open the field console and inspect each tab once so you know where your core flight information lives.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 5,
			"target_label": "Field console tabs",
			"reward_credits": 42,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
		},
		{
			"id": "intro_mining",
			"progress_key": "mine_ore",
			"short_name": "Mining Mission",
			"description": "Extract a small ore sample so you understand the basic mining loop.",
			"faction": "deepcore_consortium",
			"rep_reward": 0,
			"goal": 4,
			"target_label": "Iron asteroid fields",
			"reward_credits": 44,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
			"intro_next": "intro_ship_cargo",
		},
		{
			"id": "intro_ship_cargo",
			"progress_key": "intro_open_cargo",
			"short_name": "Ship Cargo",
			"description": "Open the cargo tab and review the ore you just brought in from the field.",
			"faction": "deepcore_consortium",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Field console cargo tab",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_mining"],
			"intro_next": "intro_station_inventory",
		},
		{
			"id": "intro_station_inventory",
			"progress_key": "intro_transfer_to_station",
			"short_name": "Station Inventory",
			"description": "Move a small ore stack into station inventory so you know how storage transfers work.",
			"faction": "deepcore_consortium",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock storage",
			"reward_credits": 20,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_ship_cargo"],
		},
		{
			"id": "intro_ship_scan",
			"progress_key": "intro_target_scan",
			"short_name": "Ship Scanning Mission",
			"description": "Use targeted scanning on a nearby object or contact to learn the close-range scanner workflow.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Nearby scan target",
			"reward_credits": 34,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
			"intro_next": "intro_world_scan",
		},
		{
			"id": "intro_world_scan",
			"progress_key": "intro_world_scan_open",
			"short_name": "World Scanning Mission",
			"description": "Open the world scan menu so you can start sweeping for resources, derelicts, and hostile contacts.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "World scan console",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_ship_scan"],
		},
		{
			"id": "intro_map",
			"progress_key": "intro_open_map",
			"short_name": "Map Mission",
			"description": "Open the map tab from the field console and review the local system layout.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Field console map tab",
			"reward_credits": 30,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
			"intro_next": "intro_fly_new_map",
		},
		{
			"id": "intro_fly_new_map",
			"progress_key": "intro_fly_new_map",
			"short_name": "Fly to New Map Section",
			"description": "Use the tactical map to jump into an adjacent section of the current system.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Adjacent map section",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_map"],
			"intro_next": "intro_jump_back_station",
		},
		{
			"id": "intro_jump_back_station",
			"progress_key": "intro_jump_back_station",
			"short_name": "Jump Back to Station",
			"description": "Return to the station map so you can close out the local navigation lesson.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock sector",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_fly_new_map"],
		},
		{
			"id": "intro_research",
			"progress_key": "intro_open_research",
			"short_name": "Research Explained",
			"description": "Visit the research bay to review how scan data turns into future ship and industry upgrades.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock research",
			"reward_credits": 26,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
		},
		{
			"id": "intro_leveling",
			"progress_key": "intro_open_skills",
			"short_name": "Player Leveling Explained",
			"description": "Open the skills tab in the field console and review the use-based skill progression readout.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Field console skills tab",
			"reward_credits": 24,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
			"intro_next": "intro_spec_training",
		},
		{
			"id": "intro_spec_training",
			"progress_key": "intro_open_training",
			"short_name": "Spec Training Explained",
			"description": "Visit the training room to review where future specialization perks will live.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock training",
			"reward_credits": 16,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_leveling"],
		},
		{
			"id": "intro_combat_controls",
			"progress_key": "intro_arm_weapons",
			"short_name": "Combat Controls",
			"description": "Toggle combat mode so you know how to switch from operations to weapons control.",
			"faction": "paladins",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Ship combat systems",
			"reward_credits": 32,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_head_to_board"],
			"intro_next": "intro_scan_hostiles",
		},
		{
			"id": "intro_scan_hostiles",
			"progress_key": "scan_hostiles",
			"short_name": "Scan Hostiles",
			"description": "Run a hostile sweep and lock onto an active threat contact.",
			"faction": "paladins",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Hostile sweep returns",
			"reward_credits": 20,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_combat_controls"],
			"intro_next": "intro_first_combat",
		},
		{
			"id": "intro_first_combat",
			"progress_key": "intro_first_combat",
			"short_name": "1st Combat",
			"description": "Destroy the marked hostile to clear your first live combat drill.",
			"faction": "paladins",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Marked hostile contact",
			"reward_credits": 24,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_scan_hostiles"],
			"intro_next": "intro_ship_maintenance",
		},
		{
			"id": "intro_ship_maintenance",
			"progress_key": "intro_open_shipyard",
			"short_name": "Ship Maintenance",
			"description": "Dock and open the shipyard so you know where to handle repairs and combat service work.",
			"faction": "paladins",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock shipyard",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_first_combat"],
		},
		{
			"id": "intro_refining",
			"progress_key": "intro_refinery_cycle",
			"short_name": "Refining Mission",
			"description": "Run one refinery cycle and watch raw ore turn into usable industrial stock.",
			"faction": "deepcore_consortium",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock refinery",
			"reward_credits": 22,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_station_inventory"],
			"intro_start_grants": [
				{"type": STARHAUL_DATA_LIB.ORE, "count": 2, "destination": "ship"},
			],
		},
		{
			"id": "intro_market",
			"progress_key": "intro_open_exchange",
			"short_name": "Market Mission",
			"description": "Open the exchange and review where station-side commodity sales are handled.",
			"faction": "freeport_assembly",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock exchange",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_station_inventory"],
			"intro_next": "intro_market_prices",
		},
		{
			"id": "intro_market_prices",
			"progress_key": "sell_value",
			"short_name": "Market Prices Explained",
			"description": "Sell a small amount of cargo so you can see prices and market payouts in action.",
			"faction": "freeport_assembly",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock exchange",
			"reward_credits": 16,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_market"],
			"intro_next": "intro_crafting_explained",
		},
		{
			"id": "intro_crafting_explained",
			"progress_key": "intro_open_crafting",
			"short_name": "Crafting Menu Explained",
			"description": "Open the crafting room and review how ingots and components turn into fabricated goods.",
			"faction": "freeport_assembly",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock crafting",
			"reward_credits": 16,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_market_prices"],
		},
		{
			"id": "intro_scan_resources",
			"progress_key": "scan_resources",
			"short_name": "Scan Resources",
			"description": "Use the world scanner to sweep for nearby resource fields and lock onto the best return.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Resource sweep returns",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_world_scan"],
		},
		{
			"id": "intro_scan_derelicts",
			"progress_key": "intro_scan_derelicts",
			"short_name": "Scan Derelicts",
			"description": "Run a derelict sweep and lock onto a wreck contact for follow-up salvage work.",
			"faction": "recovery_corps",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Derelict sweep returns",
			"reward_credits": 20,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_world_scan"],
			"intro_next": "intro_salvage",
		},
		{
			"id": "intro_salvage",
			"progress_key": "intro_salvage_scrap",
			"short_name": "Salvage Mission",
			"description": "Strip a little salvage from the marked wreck to learn the basic recovery loop.",
			"faction": "recovery_corps",
			"rep_reward": 0,
			"goal": 2,
			"target_label": "Marked salvage wreck",
			"reward_credits": 18,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": false,
			"intro_requires": ["intro_scan_derelicts"],
		},
		{
			"id": "intro_bounty_anomalies",
			"progress_key": "intro_bounty_or_anomaly",
			"short_name": "Bounty / Anomalies Explained",
			"description": "Review the bounty and anomaly scan profiles so you understand what those sweep modes will cover as the game expands.",
			"faction": "pathfinder_initiative",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "World scan reference",
			"reward_credits": 16,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_world_scan"],
			"intro_complete_on_continue": true,
			"intro_accept_badge": "EXPLAINED",
			"intro_accept_step": "Bounty and anomaly sweeps",
			"intro_accept_body": "Bounty sweeps are for tracking wanted Blackwake contacts and turning scanner focus toward active bounty targets. Anomaly sweeps are a future system for rare signals, science finds, and unusual map events. For this build, treat both as reference profiles only.",
			"intro_accept_primary": "UNDERSTOOD",
		},
		{
			"id": "intro_restock_explained",
			"progress_key": "intro_restock_visit",
			"short_name": "Restock Explained",
			"description": "Return to the shipyard and review where missile rearm support is handled.",
			"faction": "paladins",
			"rep_reward": 0,
			"goal": 1,
			"target_label": "Orbital Dock shipyard",
			"reward_credits": 14,
			"reward_xp": 0,
			"intro": true,
			"important": true,
			"persistent_offer": true,
			"intro_board_posted": true,
			"intro_requires": ["intro_ship_maintenance"],
		},
	]


static func sanitize_mission_definition(mission: Dictionary) -> Dictionary:
	var sanitized: Dictionary = mission.duplicate(true)
	match str(sanitized.get("id", "")):
		"salvage_scrap":
			sanitized["progress_key"] = "mission_delivery"
			sanitized["goal"] = 1
			sanitized["target_label"] = "Courier derelict contact"
			sanitized["mission_derelict_profile"] = "courier_hulk"
			sanitized["deliver_item"] = STARHAUL_DATA_LIB.ANCIENT_RELIC
			sanitized["deliver_amount"] = 1
		"priority_recovery":
			sanitized["progress_key"] = "mission_delivery"
			sanitized["goal"] = 1
			sanitized["target_label"] = "Survey derelict contact"
			sanitized["mission_derelict_profile"] = "research_hulk"
			sanitized["deliver_item"] = STARHAUL_DATA_LIB.QUANTUM_SHARD
			sanitized["deliver_amount"] = 1
		"contested_recovery":
			sanitized["progress_key"] = "mission_delivery"
			sanitized["goal"] = 1
			sanitized["target_label"] = "Contested patrol derelict"
			sanitized["mission_derelict_profile"] = "patrol_hulk"
			sanitized["deliver_item"] = STARHAUL_DATA_LIB.TARGETING_ARRAY
			sanitized["deliver_amount"] = 1
		"sealed_cache":
			sanitized["progress_key"] = "mission_delivery"
			sanitized["goal"] = 1
			sanitized["target_label"] = "Freighter derelict contact"
			sanitized["mission_derelict_profile"] = "freighter_hulk"
			sanitized["deliver_item"] = STARHAUL_DATA_LIB.HELIUM3
			sanitized["deliver_amount"] = 1
	return sanitized


static func actual_mission_xp_reward(mission: Dictionary) -> int:
	return int(round(float(mission.get("reward_xp", 0)) * 0.58))


static func mission_requires_delivery(mission: Dictionary) -> bool:
	return mission.has("deliver_item") and mission.has("deliver_amount")
